server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /live {
        add_header Content-Type text/plain;
        return 200 "ok";
    }

    location = /ready {
        add_header Content-Type text/plain;
        return 200 "ok";
    }

    location = /health {
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
