apiVersion: v1
kind: Secret
metadata:
  name: skycast-runtime-secrets
  namespace: skycast
type: Opaque
stringData:
  DATABASE_URL: postgresql://db-user:db-password@c-example.rw.mdb.yandexcloud.net:6432/skycast?sslmode=verify-full&sslrootcert=/etc/ssl/certs/yandex-cloud/yandex-ca.pem
  REDIS_URL: rediss://:redis-password@c-example.rw.mdb.yandexcloud.net:6380/0
  KAFKA_BOOTSTRAP_SERVERS: rc1a-example.mdb.yandexcloud.net:9091,rc1b-example.mdb.yandexcloud.net:9091,rc1c-example.mdb.yandexcloud.net:9091
  KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  KAFKA_SASL_USERNAME: kafka-user
  KAFKA_SASL_PASSWORD: kafka-password
  KAFKA_SSL_CAFILE: /etc/ssl/certs/yandex-cloud/yandex-ca.pem
