apiVersion: v1
kind: Secret
metadata:
  name: skycast-yandex-ca
  namespace: skycast
type: Opaque
stringData:
  yandex-ca.pem: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YANDEX_CLOUD_CA_CERTIFICATE
    -----END CERTIFICATE-----
