apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skycast
  namespace: skycast
spec:
  ingressClassName: alb
  rules:
    - host: analytics.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analytics-api
                port:
                  number: 80
    - host: forecast.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forecast-service
                port:
                  number: 80
    - host: telemetry.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 80
